### ISSUE TITLE
pessimistic stack sizes 

### ISSUE THREAD

**Issue by TorgeH** [munkki84/SailFreeCell#6]
When moving a stack in the presence of free columns, the fact that these columns can receive stacks is completely ignored leading to valid stack moves being rejected.
I have a solution for this but it includes a lot of refactoring -- due to the fact that I had to change the way free cells are stored and updated anyway -- up to the point that I have done aeay with Rules.js completely.
I'd like to hear what you think about it before I make the next pull request.

**Comment by munkki84** [comment]
New class structure looks better in my opinion. So it's fine to refactor those classes. Only thing with correct stack moves is, it might take some player skill away, but that's a player preference.

**Comment by TorgeH** [comment]
I have added some comments to the diff of the pull-request.
Including the pointer to the place where the logic is changed.
I could prepare a new pull request with only the refactorings if that helps.
Or we start discussing user preferences?
What I would really like to see would be a new release. Even if it is only for the 2 already merged fixes.
From the comments in the jolla store you can see that people are often confused about how to start a new game.

**Comment by munkki84** [comment]
I think these changes are fine if there is nothing urgent to add. I'll do some testing that majority of things work and try to push a new release to Jolla store on the weekend.

**Comment by munkki84** [comment]
Found a bug. If you move a stack on a empty freecell, logic let's you move a too big of a stack, since it doesn't count that moving to a empty freecell reduces amount of empty freecells.

**Comment by munkki84** [comment]
Bug is fixed and new version is submitted to jolla store it should be up in few days.
